export const navLinks=[
    {
        id:"home",
        title:"Home"
    },
    {
        id:"about",
        title:"About"
    },
    {
        id:"services",
        title:"Services"
    },
    {
        id:"repair&services",
        title:"Repair & Services"
    },
    {
        id:"blog",
        title:"Blog"
    },
    {
        id:"booking",
        title:"Booking"
    },
    {
        id:"contacts",
        title:"Contacts"
    },
]